const buildMachinePayload = (machine = {}) => ({
  id: '',
  name: '',
  model: '',
  type: '',
  ip: '',
  hasSensors: false,
  node: null,
  icon: 'gear',
  sensors: [],
  status: 'Arrêt',
  sante: 100,
  production: 0,
  objectif: 0,
  efficacite: 0,
  heures: 0,
  temperature: 0,
  courant: 0,
  vibration: 0,
  rpm: 0,
  pression: null,
  protocol: '—',
  broker: '—',
  latence: '—',
  uptime: '—',
  chipModel: '—',
  machId: machine.id ? `MACH-${String(machine.id).toUpperCase()}` : null,
  problems: [],
  fonctions: [],
  isBase: false,
  ...machine,
});

const BASE_MACHINE_CATALOG = [
  buildMachinePayload({
    id: 'haas-cnc',
    name: 'HAAS CNC',
    model: 'HAAS VF-2SS',
    type: 'Fraiseuse CNC',
    ip: '192.168.1.101',
    icon: 'gear',
    status: 'En marche',
    sante: 85,
    production: 686,
    objectif: 700,
    efficacite: 93.6,
    heures: 156,
    temperature: 43.5,
    machId: 'MACH-HAAS-001',
    isBase: true,
  }),
  buildMachinePayload({
    id: 'agie-cut',
    name: 'Agie Cut',
    model: 'AgieCharmilles CUT 20 P',
    type: 'Électroérosion à fil',
    ip: '192.168.1.102',
    icon: 'bolt',
    status: 'En marche',
    sante: 78,
    production: 458,
    objectif: 450,
    efficacite: 91.3,
    heures: 142,
    temperature: 45.1,
    machId: 'MACH-AGIE-002',
    isBase: true,
  }),
  buildMachinePayload({
    id: 'rectifieuse',
    name: 'Rectifieuse',
    model: 'Surface Grinding SG-400',
    type: 'Rectification plane',
    ip: '192.168.1.103',
    icon: 'gear',
    hasSensors: true,
    node: 'ESP32-NODE-03',
    sensors: ['ADXL345', 'SCT-013', 'Hall Sensor'],
    status: 'En marche',
    sante: 71,
    production: 312,
    objectif: 350,
    efficacite: 88.4,
    heures: 98,
    temperature: 38.2,
    courant: 12.3,
    vibration: 1.4,
    rpm: 3096,
    protocol: 'WiFi 2.4GHz',
    broker: '192.168.1.10:1883',
    latence: '12 ms',
    uptime: '8h 45min',
    chipModel: 'ESP32-WROOM-32D',
    machId: 'MACH-RCT-003',
    fonctions: [
      { title: 'Rectification plane', desc: 'Surfacage de pieces metalliques avec precision +/-0.01mm' },
      { title: 'Rectification cylindrique', desc: 'Finition de surfaces cylindriques internes et externes' },
      { title: 'Dressage de meule', desc: 'Reconditionnement automatique de la meule abrasive' },
    ],
    isBase: true,
  }),
  buildMachinePayload({
    id: 'agie-drill',
    name: 'Agie Drill',
    model: 'AgieCharmilles DRILL 20',
    type: 'Percage EDM',
    ip: '192.168.1.104',
    icon: 'drill',
    status: 'En marche',
    sante: 82,
    production: 390,
    objectif: 400,
    efficacite: 89.8,
    heures: 120,
    temperature: 41.2,
    machId: 'MACH-DRL-004',
    isBase: true,
  }),
  buildMachinePayload({
    id: 'compresseur',
    name: 'Compresseur ABAC',
    model: 'ABAC FORMULA 7.5 - 270L',
    type: 'Compresseur a vis',
    ip: '192.168.1.105',
    imageUrl: 'https://www.atlascopco.com/content/dam/brands/ABAC/products/screw-compressors/formula/formula-5%2C5-30kw/formula-5-5-30-kw-abac-0000.png/jcr%3Acontent/renditions/cq5dam.web.800.800.png',
    icon: 'wrench',
    hasSensors: true,
    node: 'compresseur',
    sensors: ['ADXL345', 'SCT-013', 'Pression'],
    status: 'En marche',
    sante: 90,
    heures: 210,
    temperature: 37.0,
    courant: 8.2,
    vibration: 0.3,
    pression: 0,
    protocol: 'WiFi 2.4GHz',
    broker: 'mqtt',
    chipModel: 'ESP32',
    machId: 'MACH-CMP-005',
    isBase: true,
  }),
  buildMachinePayload({
    id: 'tour-cnc',
    name: 'Tour CNC',
    model: 'MAZAK QT-PRIMOS 150',
    type: 'Tour a commande numerique',
    ip: '192.168.1.106',
    icon: 'gear',
    status: 'En marche',
    sante: 90,
    production: 523,
    objectif: 500,
    efficacite: 96.2,
    heures: 178,
    temperature: 41.0,
    machId: 'MACH-TRN-006',
    isBase: true,
  }),
];

const ensureBaseMachines = async ({ MachineModel, logger = console } = {}) => {
  if (!MachineModel) return;

  await MachineModel.bulkWrite(
    BASE_MACHINE_CATALOG.map((machine) => ({
      updateOne: {
        filter: { id: machine.id },
        update: { $setOnInsert: machine },
        upsert: true,
      },
    }))
  );

  logger.log(`[machines] base catalog ready (${BASE_MACHINE_CATALOG.length})`);
};

const buildDerivedMachine = ({ id, name, hasSensors = false, node = null } = {}) =>
  buildMachinePayload({
    id,
    name,
    hasSensors,
    node,
    status: 'Arrêt',
    isBase: false,
    isDerived: true,
  });

module.exports = {
  BASE_MACHINE_CATALOG,
  buildMachinePayload,
  buildDerivedMachine,
  ensureBaseMachines,
};
